build:
    environment:
        variables:
            DB_HOSTNAME: '127.0.0.1'
            DB_DATABASE: 'rest_api_slim_php'
            DB_USERNAME: 'root'
            DB_PASSWORD: ''
        php:
            version: 7.1
    project_setup:
        before:
            - mysql -e "CREATE DATABASE rest_api_slim_php"
            - mysql rest_api_slim_php < database/database.sql
        override:
            - php-scrutinizer-run
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
