version: '3.7'
services: 

  backend:
    build: .
    image: backend
    container_name: backend
    restart: always
    networks:
      - internal
    labels:
      - "traefik.enable=false"

  db_sers:
    image: mariadb
    container_name: db_sers
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=SERS
    volumes:
      - /data/db_sers:/var/lib/mysql
      - ./Database/sers.sql:/docker-entrypoint-initdb.d/dump.sql
    networks: 
      - internal
    labels:
      - traefik.enable=false

networks:
  internal:
    external: false
